// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xumevtuhzjdfspudceph.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh1bWV2dHVoempkZnNwdWRjZXBoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExMDYxNDUsImV4cCI6MjA1NjY4MjE0NX0.8Bk6A60nm-V-DlsrmKFTbneWwQeQ_UOy6n8DZJ5DlNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);